### ISSUE TITLE
`random_string` uses built-in `shuffle` function, which uses the php `rand` function

### ISSUE THREAD

**Issue by svbnet** [brandonwamboldt/utilphp#51]
`mt_rand` is the preferred replacement for `rand` and `shuffle` as it is more entropic and 4x faster.

http://nz2.php.net/manual/en/function.mt-rand.php

https://github.com/php/php-src/blob/fc33f52d8c25997dd0711de3e07d0dc260a18c11/ext/standard/array.c#L1916

**Comment by brandonwamboldt** [comment]
I've changed `random_string` to use `mt_rand` instead of `shuffle`. This has the side effect of making the function about 2x faster normally (since we aren't shuffling the array constantly), and 10% slower when generating random strings with no duplicate characters (because of using `array_splice`).
